version: '3.8'

services:
  php:
    build: ./www
    container_name: app-php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: app-redis
    ports:
      - "6380:6379"

volumes:
  db_data:
